name: Pull Request
on:
  pull_request_target:
    types: [edited, opened, reopened, synchronize, closed]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Report Pull Request environment
      uses: actions/github-script@v6
      continue-on-error: true
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `
          Pull Request Target action triggered.

          - Base Ref: ${{ github.base_ref }}
          - Head Ref: ${{ github.head_ref }}
          - Ref: ${{ github.ref }}
          - Event Name: ${{ github.event_name }}
          `
          })
